-- AlterEnum: Add GST_ITEM_WISE to GSTMode enum on company, invoice, estimate tables
ALTER TABLE `company` MODIFY COLUMN `gstMode` ENUM('GST_VISIBLE','GST_INCLUDED_HIDDEN','GST_IGST','NO_GST','GST_ITEM_WISE') NOT NULL DEFAULT 'GST_VISIBLE';
ALTER TABLE `invoice` MODIFY COLUMN `gstMode` ENUM('GST_VISIBLE','GST_INCLUDED_HIDDEN','GST_IGST','NO_GST','GST_ITEM_WISE') NOT NULL DEFAULT 'GST_VISIBLE';
ALTER TABLE `estimate` MODIFY COLUMN `gstMode` ENUM('GST_VISIBLE','GST_INCLUDED_HIDDEN','GST_IGST','NO_GST','GST_ITEM_WISE') NOT NULL DEFAULT 'GST_VISIBLE';
