-- CreateTable
CREATE TABLE `advance_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyId` INT NOT NULL,
  `branchId` INT NULL,
  `orderNumber` VARCHAR(191) NOT NULL,
  `orderDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deliveryDate` DATE NOT NULL,
  `deliveryTime` VARCHAR(191) NULL,
  `invoiceDate` DATE NOT NULL,
  `noOfPax` INT NULL,
  `categoryName` VARCHAR(191) NULL,
  `serviceName` VARCHAR(191) NULL,
  `customerMobile` VARCHAR(191) NULL,
  `customerName` VARCHAR(191) NULL,
  `address` TEXT NULL,
  `landmark` VARCHAR(191) NULL,
  `additionalMobile` VARCHAR(191) NULL,
  `customerGstNo` VARCHAR(191) NULL,
  `companyName` VARCHAR(191) NULL,
  `referenceNumber` VARCHAR(191) NULL,
  `remarks` TEXT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discountPercent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `discountAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `taxAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `grandTotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `paidAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `dueAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `paymentMode` VARCHAR(191) NOT NULL DEFAULT 'CASH',
  `cashAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `cardAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `upiAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `walletAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `orderStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `createdByUserId` INT NOT NULL,
  `updatedByUserId` INT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `AdvanceOrder_companyId_orderNumber_key`(`companyId`, `orderNumber`),
  INDEX `AdvanceOrder_branchId_fkey`(`branchId`),
  INDEX `AdvanceOrder_createdByUserId_fkey`(`createdByUserId`),
  INDEX `AdvanceOrder_updatedByUserId_fkey`(`updatedByUserId`),

  CONSTRAINT `AdvanceOrder_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `AdvanceOrder_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branch`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `AdvanceOrder_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `AdvanceOrder_updatedByUserId_fkey` FOREIGN KEY (`updatedByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `advance_order_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `advanceOrderId` INT NOT NULL,
  `companyId` INT NOT NULL,
  `productId` INT NULL,
  `productName` VARCHAR(191) NOT NULL,
  `quantity` DECIMAL(12,2) NOT NULL,
  `unitPrice` DECIMAL(12,2) NOT NULL,
  `discountPercent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `discountAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `taxPercent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `taxAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(12,2) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  INDEX `AdvanceOrderItem_advanceOrderId_fkey`(`advanceOrderId`),
  INDEX `AdvanceOrderItem_productId_fkey`(`productId`),
  INDEX `AdvanceOrderItem_companyId_fkey`(`companyId`),

  CONSTRAINT `AdvanceOrderItem_advanceOrderId_fkey` FOREIGN KEY (`advanceOrderId`) REFERENCES `advance_order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `AdvanceOrderItem_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `AdvanceOrderItem_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
