export interface PORecord {
  id: string;
  sNo: number;
  poDate: string;
  poNo: string;
  branchName: string;
  noOfProducts: number;
  grandTotal: number;
  remarks: string;
  vendorName: string;
  createdDate: string;
  requestStatus: "Pending" | "Approved" | "Rejected" | "Completed";
}

export const samplePOs: PORecord[] = [
  {
    id: "1",
    sNo: 1,
    poDate: "28/07/2026",
    poNo: "PO-0001",
    branchName: "Main Branch",
    noOfProducts: 5,
    grandTotal: 12500.00,
    remarks: "Monthly restock",
    vendorName: "Fresh Foods Ltd",
    createdDate: "28/07/2026",
    requestStatus: "Approved",
  },
  {
    id: "2",
    sNo: 2,
    poDate: "27/07/2026",
    poNo: "PO-0002",
    branchName: "Main Branch",
    noOfProducts: 3,
    grandTotal: 8750.50,
    remarks: "Urgent requirement",
    vendorName: "Spice World",
    createdDate: "27/07/2026",
    requestStatus: "Pending",
  },
  {
    id: "3",
    sNo: 3,
    poDate: "26/07/2026",
    poNo: "PO-0003",
    branchName: "Second Branch",
    noOfProducts: 8,
    grandTotal: 23400.00,
    remarks: "Weekly order",
    vendorName: "Grain Traders",
    createdDate: "26/07/2026",
    requestStatus: "Rejected",
  },
  {
    id: "4",
    sNo: 4,
    poDate: "25/07/2026",
    poNo: "PO-0004",
    branchName: "Main Branch",
    noOfProducts: 2,
    grandTotal: 5600.00,
    remarks: "Cleaning supplies",
    vendorName: "Oil Mart",
    createdDate: "25/07/2026",
    requestStatus: "Completed",
  },
  {
    id: "5",
    sNo: 5,
    poDate: "24/07/2026",
    poNo: "PO-0005",
    branchName: "Second Branch",
    noOfProducts: 4,
    grandTotal: 9800.00,
    remarks: "Detergent stock",
    vendorName: "Dairy Direct",
    createdDate: "24/07/2026",
    requestStatus: "Approved",
  },
  {
    id: "6",
    sNo: 6,
    poDate: "23/07/2026",
    poNo: "PO-0006",
    branchName: "Main Branch",
    noOfProducts: 6,
    grandTotal: 15200.00,
    remarks: "Festival season prep",
    vendorName: "Fresh Foods Ltd",
    createdDate: "23/07/2026",
    requestStatus: "Pending",
  },
  {
    id: "7",
    sNo: 7,
    poDate: "22/07/2026",
    poNo: "PO-0007",
    branchName: "Second Branch",
    noOfProducts: 10,
    grandTotal: 34500.00,
    remarks: "Bulk order",
    vendorName: "Sweet Supply Co",
    createdDate: "22/07/2026",
    requestStatus: "Approved",
  },
  {
    id: "8",
    sNo: 8,
    poDate: "21/07/2026",
    poNo: "PO-0008",
    branchName: "Main Branch",
    noOfProducts: 3,
    grandTotal: 7200.00,
    remarks: "Low stock items",
    vendorName: "Veggie Farm",
    createdDate: "21/07/2026",
    requestStatus: "Completed",
  },
  {
    id: "9",
    sNo: 9,
    poDate: "20/07/2026",
    poNo: "PO-0009",
    branchName: "Second Branch",
    noOfProducts: 7,
    grandTotal: 18900.00,
    remarks: "Monthly requirement",
    vendorName: "Grain Traders",
    createdDate: "20/07/2026",
    requestStatus: "Rejected",
  },
  {
    id: "10",
    sNo: 10,
    poDate: "19/07/2026",
    poNo: "PO-0010",
    branchName: "Main Branch",
    noOfProducts: 5,
    grandTotal: 11300.00,
    remarks: "New recipe items",
    vendorName: "Spice World",
    createdDate: "19/07/2026",
    requestStatus: "Pending",
  },
];
