export interface IndentRecord {
  id: string;
  sNo: number;
  indentNo: string;
  branchName: string;
  deptName: string;
  noOfProducts: number;
  remarks: string;
  createdDate: string;
  indentType: string;
  indentTo: string;
  requestStatus: "Pending" | "Approved" | "Rejected" | "Completed";
}

export const sampleIndents: IndentRecord[] = [
  {
    id: "1",
    sNo: 1,
    indentNo: "IND-0001",
    branchName: "Main Branch",
    deptName: "Kitchen",
    noOfProducts: 5,
    remarks: "Monthly restock",
    createdDate: "28/07/2026",
    indentType: "Inventory",
    indentTo: "Central Store",
    requestStatus: "Approved",
  },
  {
    id: "2",
    sNo: 2,
    indentNo: "IND-0002",
    branchName: "Main Branch",
    deptName: "Production",
    noOfProducts: 3,
    remarks: "Urgent requirement",
    createdDate: "27/07/2026",
    indentType: "Inventory",
    indentTo: "Central Store",
    requestStatus: "Pending",
  },
  {
    id: "3",
    sNo: 3,
    indentNo: "IND-0003",
    branchName: "Second Branch",
    deptName: "Kitchen",
    noOfProducts: 8,
    remarks: "Weekly order",
    createdDate: "26/07/2026",
    indentType: "Production",
    indentTo: "Head Office",
    requestStatus: "Rejected",
  },
  {
    id: "4",
    sNo: 4,
    indentNo: "IND-0004",
    branchName: "Main Branch",
    deptName: "Housekeeping",
    noOfProducts: 2,
    remarks: "Cleaning supplies",
    createdDate: "25/07/2026",
    indentType: "Inventory",
    indentTo: "Central Store",
    requestStatus: "Completed",
  },
  {
    id: "5",
    sNo: 5,
    indentNo: "IND-0005",
    branchName: "Second Branch",
    deptName: "Laundry",
    noOfProducts: 4,
    remarks: "Detergent stock",
    createdDate: "24/07/2026",
    indentType: "Inventory",
    indentTo: "Central Store",
    requestStatus: "Approved",
  },
  {
    id: "6",
    sNo: 6,
    indentNo: "IND-0006",
    branchName: "Main Branch",
    deptName: "Kitchen",
    noOfProducts: 6,
    remarks: "Festival season prep",
    createdDate: "23/07/2026",
    indentType: "Inventory",
    indentTo: "Head Office",
    requestStatus: "Pending",
  },
  {
    id: "7",
    sNo: 7,
    indentNo: "IND-0007",
    branchName: "Second Branch",
    deptName: "Production",
    noOfProducts: 10,
    remarks: "Bulk order",
    createdDate: "22/07/2026",
    indentType: "Production",
    indentTo: "Central Store",
    requestStatus: "Approved",
  },
  {
    id: "8",
    sNo: 8,
    indentNo: "IND-0008",
    branchName: "Main Branch",
    deptName: "Kitchen",
    noOfProducts: 3,
    remarks: "Low stock items",
    createdDate: "21/07/2026",
    indentType: "Inventory",
    indentTo: "Central Store",
    requestStatus: "Completed",
  },
  {
    id: "9",
    sNo: 9,
    indentNo: "IND-0009",
    branchName: "Second Branch",
    deptName: "Housekeeping",
    noOfProducts: 7,
    remarks: "Monthly requirement",
    createdDate: "20/07/2026",
    indentType: "Inventory",
    indentTo: "Head Office",
    requestStatus: "Rejected",
  },
  {
    id: "10",
    sNo: 10,
    indentNo: "IND-0010",
    branchName: "Main Branch",
    deptName: "Production",
    noOfProducts: 5,
    remarks: "New recipe items",
    createdDate: "19/07/2026",
    indentType: "Production",
    indentTo: "Central Store",
    requestStatus: "Pending",
  },
];
